// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects the runtime capability profile for a new or forked thread.
 *
 * `Standard` preserves the normal Agent runtime. `PromptOptimization` is a
 * temporary, read-only thread that only exposes capabilities needed to
 * inspect context and improve a prompt.
 */
export type ThreadMode = "standard" | "promptOptimization";
